services:
  - type: web
    plan: free
    name: core
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: "gunicorn core.wsgi:application"
    autoDeploy: true
